# Site settings
title: Fully Studios
email: hi@fullystudios.se
tel: "+46 738 07 30 72"
description: Fully Studios - This site is under construction.
adress: Victoriapassagen,<br>Södra Larmgatan 14,<br>411 16 Göteborg
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fullystudios.github.io" # the base hostname & protocol for your site
twitter: "https://twitter.com/fullyflared_se"
github:  "https://github.com/fullystudios"
facebook: "https://www.facebook.com/Fully-Flared-Digital-Agency-150488108297019/?ref=ts&fref=ts"
vimeo: "https://vimeo.com/fullystudios"
instagram: "https://www.instagram.com/fullystudios/"

# Papricaklubben
case_highlight1_id: 6

# Collector
case_highlight2_id: 1

# KappAhl
case_highlight3_id: 2

# Links
works: "/works"
about: "/about"

# Custom post types 
collections:
  work:
    output: true
    permalink: /:collection/:title/
  curious-about:
    output: true
    permalink: /:collection/:title/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "curious-about"
    values:
      layout: "curious"
      button-text: Read all about it
      background-color: "#f2f2f2"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "work"
      button-text: View case
      background-color: "#f2f2f2"

# Build settings
highlighter: rouge
markdown: kramdown
source: src
destination: public
sass:
  sass_dir: assets/css/modules
  style: compressed

# live reload
livereload: true
reload_port: 5678

# gems
gems:
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-sitemap
  - jekyll-redirect-from

# plugin settings
autoprefixer:
  browsers:
  - last 2 versions

exclude: ['node_modules', 'webpack', 'Gemfile', 'Gemfile.lock', 'Rakefile']
