# Site settings
title: Fully Studios
email: hello@fullystudios.se
tel: "+46 738 07 30 72"
description: Fully Studios is a Swedish web and film studio, specializing in motion on the web.
adress: Victoriapassagen,<br>Södra Larmgatan 14,<br>411 16 Göteborg
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/fullystudios" # for demo site on demo.fullyflared.se/fullystudios
url: "http://stage.fullystudios.se" # the base hostname & protocol for your site
absolute_path: "http://stage.fullystudios.se" # should be https://fullystudios.se on the live site
shareimage: "images/fully-studios-facebook-share-image.png"
twitter: "https://twitter.com/fullyflared_se"
github:  "https://github.com/fullystudios"
facebook: "https://www.facebook.com/Fully-Flared-Digital-Agency-150488108297019/?ref=ts&fref=ts"
vimeo: "https://vimeo.com/fullystudios"
instagram: "https://www.instagram.com/fullystudios/"
newsflash: |
  ### News flash!

  We got a new name, a new logo and a new way of announcing news flashes.

# newsflash_buttontext: Check it out
newsflash_buttonurl: /about

# Papricaklubben
case_highlight1_id: 5

# Collector
case_highlight2_id: 1

# Tanumstrand
case_highlight3_id: 2

# Links
works: "/work"
about: "/about"

# Custom post types 
collections:
  work:
    output: true
    permalink: /:collection/:title/
  curious-about:
    output: true
    permalink: /:collection/:title/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "curious-about"
    values:
      layout: "curious"
      button-text: Read all about it
      background-color: "#f8f8f8"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "work"
      button-text: View case
      background-color: "#f8f8f8"

# Build settings
highlighter: rouge
markdown: kramdown
source: src
destination: public
sass:
  sass_dir: assets/css/modules
  style: compressed

# live reload
livereload: true
reload_port: 5678

# gems
plugins_dir:
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-sitemap
  - jekyll-redirect-from

# plugin settings
autoprefixer:
  browsers:
  - last 2 versions

exclude: ['node_modules', 'webpack', 'Gemfile', 'Gemfile.lock', 'Rakefile']
